version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  audibene-test:
    image: sahilmutreja/audibene-test
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - TEST_SUITE_FILE=audibene-test.xml
    volumes:
      - ./test-result:/usr/share/audibene-test/test-output