version: "3"
services:
  hub:
    image: seleniarm/hub:4.1.2-20220227
    ports:
      - "4444:4444"

  chrome:
    image: seleniarm/node-chromium:4.1.2-20220227
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: seleniarm/node-firefox:4.1.2-20220227
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  audibene-test:
    image: sahilmutreja/audibene-test
    shm_size: '1g'
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - TEST_SUITE_FILE=audibene-test.xml
    volumes:
      - ./test-result:/usr/share/audibene-test/test-output